### ISSUE TITLE
Infografia Fases de gestión de proyectos de software.

### ISSUE THREAD

**Issue by Graciela2000** [SistemasTecTlaxiaco/infografia-Graciela2000-1#2]
[Fases de gestión de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Graciela2000-1/files/7118047/Fases.de.gestion.de.proyectos.de.software.pdf)

**Comment by Nancy2050** [comment]
Calificación: 16%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
